//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWARD
    {
        public int AWARD_ID { get; set; }
        public Nullable<int> PRVDR_ID { get; set; }
        public string FCILITY_ID { get; set; }
        public string AWARD_NM { get; set; }
        public string AWARD_DSC { get; set; }
        public string EFFECTIVE_DT { get; set; }
        public string EXPIRE_DT { get; set; }
    
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
