//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE_RAW
    {
        public int PRVDR_ID { get; set; }
        public string LEVEL_DSC { get; set; }
        public string DEGREE_DSC { get; set; }
        public string INSTITUTION_DSC { get; set; }
        public string INSTITUTION_CITY { get; set; }
        public string INSTITUTION_ST { get; set; }
        public string PROGRAM_DSC { get; set; }
        public string START_DT { get; set; }
        public string END_DT { get; set; }
        public string GRADUATED_FLG { get; set; }
        public string ED_SPECIALITY { get; set; }
    }
}
