//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileImportSetting
    {
        public string FileImportSettingID { get; set; }
        public string FileImportSettingValue { get; set; }
        public long DEX_ROW { get; set; }
        public System.DateTimeOffset DEX_ROW_TS { get; set; }
    }
}
