//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOCATION_ID { get; set; }
        public Nullable<int> PRVDR_ID { get; set; }
        public string ADDRESS_SEQ { get; set; }
        public string PRIMARYADDRESS_FLG { get; set; }
        public string PRACTICE_NM { get; set; }
        public string ADDRESS_ONE { get; set; }
        public string ADDRESS_TWO { get; set; }
        public string CITY { get; set; }
        public string ST { get; set; }
        public string COUNTY { get; set; }
        public string ZIP_CODE { get; set; }
        public string PHONE_NBR { get; set; }
        public string FAX_NBR { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string HOURS1 { get; set; }
        public string HOURS2 { get; set; }
        public string OPENPRACTICE_DSC { get; set; }
        public string OPENLATE_FLG { get; set; }
        public string OPENEARLY_FLG { get; set; }
        public string OPENWEEKEND_FLG { get; set; }
        public string AFTERHOURSINSTRUCTIONS { get; set; }
        public string FACILITY_ID { get; set; }
        public string ADA_FLG { get; set; }
    
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
