//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATIONINSURANCE
    {
        public int LOCATIONINSURANCE_ID { get; set; }
        public Nullable<int> PRVDR_ID { get; set; }
        public string ADDRESS_SEQ { get; set; }
        public string PLAN_CODE { get; set; }
        public string PLAN_NM { get; set; }
        public string EXCEPTIONS { get; set; }
        public string PCP_FLG { get; set; }
    
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
