//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER_RAW
    {
        public int PRVDR_ID { get; set; }
        public string FIRST_NM { get; set; }
        public string MIDDLE_NM { get; set; }
        public string LAST_NM { get; set; }
        public string TITLE_NM { get; set; }
        public string INTERMOUNTAIN_FLG { get; set; }
        public string IMGPROVIDER_FLG { get; set; }
        public string MYHEALTHPROVIDER_FLG { get; set; }
        public string SELECTHEALTH_FLG { get; set; }
        public string SH_IDAHOFLG { get; set; }
        public string STLUKESPROVIDER_FLG { get; set; }
        public string GENDER { get; set; }
        public string PHOTO_URL { get; set; }
        public string VIDEO_URL { get; set; }
        public string ACCEPTINGNEWPATIENTS_FLG { get; set; }
        public string PRACTICES_OB { get; set; }
        public string BIO_INTERESTS { get; set; }
        public string PROFESSIONAL_POSITIONS { get; set; }
        public string PRACTICE_FOCUS { get; set; }
        public string NPI { get; set; }
    }
}
