//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVIDER()
        {
            this.AWARDs = new HashSet<AWARD>();
            this.BOARDCERTIFICATIONs = new HashSet<BOARDCERTIFICATION>();
            this.DEGREEs = new HashSet<DEGREE>();
            this.HOSPAFFILIATIONs = new HashSet<HOSPAFFILIATION>();
            this.LANGUAGEs = new HashSet<LANGUAGE>();
            this.LOCATIONs = new HashSet<LOCATION>();
            this.LOCATIONINSURANCEs = new HashSet<LOCATIONINSURANCE>();
            this.MEMBERSHIPs = new HashSet<MEMBERSHIP>();
            this.PATIENTEDUCATIONs = new HashSet<PATIENTEDUCATION>();
            this.SPECIALTies = new HashSet<SPECIALTY>();
            this.TRAININGs = new HashSet<TRAINING>();
            this.WEBRESOURCEs = new HashSet<WEBRESOURCE>();
        }
    
        public int PRVDR_ID { get; set; }
        public string FIRST_NM { get; set; }
        public string MIDDLE_NM { get; set; }
        public string LAST_NM { get; set; }
        public string TITLE_NM { get; set; }
        public string INTERMOUNTAIN_FLG { get; set; }
        public string IMGPROVIDER_FLG { get; set; }
        public string MYHEALTHPROVIDER_FLG { get; set; }
        public string SELECTHEALTH_FLG { get; set; }
        public string SH_IDAHOFLG { get; set; }
        public string STLUKESPROVIDER_FLG { get; set; }
        public string GENDER { get; set; }
        public string PHOTO_URL { get; set; }
        public string VIDEO_URL { get; set; }
        public string ACCEPTINGNEWPATIENTS_FLG { get; set; }
        public string PRACTICES_OB { get; set; }
        public string BIO_INTERESTS { get; set; }
        public string PROFESSIONAL_POSITIONS { get; set; }
        public string PRACTICE_FOCUS { get; set; }
        public string NPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AWARD> AWARDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOARDCERTIFICATION> BOARDCERTIFICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEGREE> DEGREEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSPAFFILIATION> HOSPAFFILIATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LANGUAGE> LANGUAGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATION> LOCATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATIONINSURANCE> LOCATIONINSURANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERSHIP> MEMBERSHIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENTEDUCATION> PATIENTEDUCATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIALTY> SPECIALTies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING> TRAININGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEBRESOURCE> WEBRESOURCEs { get; set; }
    }
}
