//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRG_DBTESTSEntities : DbContext
    {
        public FRG_DBTESTSEntities()
            : base("name=FRG_DBTESTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ALL_ACTIONS> ALL_ACTIONS { get; set; }
        public virtual DbSet<AWARD> AWARDs { get; set; }
        public virtual DbSet<AWARD_ACTION> AWARD_ACTION { get; set; }
        public virtual DbSet<BOARDCERTIFICATION> BOARDCERTIFICATIONs { get; set; }
        public virtual DbSet<BOARDCERTIFICATION_ACTION> BOARDCERTIFICATION_ACTION { get; set; }
        public virtual DbSet<DEGREE> DEGREEs { get; set; }
        public virtual DbSet<DEGREE_ACTION> DEGREE_ACTION { get; set; }
        public virtual DbSet<HOSPAFFILIATION> HOSPAFFILIATIONs { get; set; }
        public virtual DbSet<HOSPAFFILIATION_ACTION> HOSPAFFILIATION_ACTION { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<LANGUAGE_ACTION> LANGUAGE_ACTION { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<LOCATION_ACTION> LOCATION_ACTION { get; set; }
        public virtual DbSet<LOCATIONINSURANCE> LOCATIONINSURANCEs { get; set; }
        public virtual DbSet<LOCATIONINSURANCE_ACTION> LOCATIONINSURANCE_ACTION { get; set; }
        public virtual DbSet<MEMBERSHIP> MEMBERSHIPs { get; set; }
        public virtual DbSet<MEMBERSHIP_ACTION> MEMBERSHIP_ACTION { get; set; }
        public virtual DbSet<PATIENTEDUCATION> PATIENTEDUCATIONs { get; set; }
        public virtual DbSet<PATIENTEDUCATION_ACTION> PATIENTEDUCATION_ACTION { get; set; }
        public virtual DbSet<PROVIDER> PROVIDERs { get; set; }
        public virtual DbSet<PROVIDER_ACTION> PROVIDER_ACTION { get; set; }
        public virtual DbSet<SITECORELOCATION> SITECORELOCATIONs { get; set; }
        public virtual DbSet<SPECIALTY> SPECIALTies { get; set; }
        public virtual DbSet<SPECIALTY_ACTION> SPECIALTY_ACTION { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRAINING> TRAININGs { get; set; }
        public virtual DbSet<TRAINING_ACTION> TRAINING_ACTION { get; set; }
        public virtual DbSet<WEBRESOURCE> WEBRESOURCEs { get; set; }
        public virtual DbSet<WEBRESOURCE_ACTION> WEBRESOURCE_ACTION { get; set; }
        public virtual DbSet<FileImportSetting> FileImportSettings { get; set; }
        public virtual DbSet<application_USZipcodes> application_USZipcodes { get; set; }
        public virtual DbSet<BOARDCERTIFICATION_RAW> BOARDCERTIFICATION_RAW { get; set; }
        public virtual DbSet<DEGREE_RAW> DEGREE_RAW { get; set; }
        public virtual DbSet<HOSPAFFILIATION_RAW> HOSPAFFILIATION_RAW { get; set; }
        public virtual DbSet<LOCATION_RAW> LOCATION_RAW { get; set; }
        public virtual DbSet<LOCATIONINSURANCE_RAW> LOCATIONINSURANCE_RAW { get; set; }
        public virtual DbSet<PROVIDER_RAW> PROVIDER_RAW { get; set; }
        public virtual DbSet<SH_COUNTY> SH_COUNTY { get; set; }
        public virtual DbSet<SH_COUNTYPLANINTERSECTION> SH_COUNTYPLANINTERSECTION { get; set; }
        public virtual DbSet<SH_OPTIONALBENEFITS> SH_OPTIONALBENEFITS { get; set; }
        public virtual DbSet<SH_PLAN> SH_PLAN { get; set; }
        public virtual DbSet<SH_ZIPCODE> SH_ZIPCODE { get; set; }
        public virtual DbSet<SH_ZIPCODECOUNTYINTERSECTION> SH_ZIPCODECOUNTYINTERSECTION { get; set; }
        public virtual DbSet<SPECIALTY_RAW> SPECIALTY_RAW { get; set; }
        public virtual DbSet<STEPEXPRESSREGISTRATION> STEPEXPRESSREGISTRATIONs { get; set; }
        public virtual DbSet<TRAINING_RAW> TRAINING_RAW { get; set; }
    }
}
