//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDER_ACTION
    {
        public long ID { get; set; }
        public int PRVDR_ID { get; set; }
        public string Action { get; set; }
        public string ModifiedField { get; set; }
    }
}
