//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_COUNTY
    {
        public int CountyId { get; set; }
        public string County { get; set; }
        public bool Covered { get; set; }
        public bool CoveredNextYear { get; set; }
        public string State { get; set; }
        public string Brand { get; set; }
        public string ServiceArea { get; set; }
    }
}
