//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_OPTIONALBENEFITS
    {
        public int PlanId { get; set; }
        public string PlanHeader { get; set; }
        public string BenefitDescription { get; set; }
        public string ServiceArea { get; set; }
        public string Premium { get; set; }
        public string DentalDeductible { get; set; }
        public string AnnualMedicalDeductible { get; set; }
        public string OralExaminations { get; set; }
        public string Cleanings { get; set; }
        public string XRays { get; set; }
        public string Basic { get; set; }
        public string Major { get; set; }
        public string Orthodontics { get; set; }
        public string PlusPlanHeader { get; set; }
        public string PremiumPlus { get; set; }
        public string EyewearBenefit { get; set; }
        public string DentalDeductiblePlus { get; set; }
        public string AnnualMaximumPlanPayment { get; set; }
        public string OralExaminationsPlus { get; set; }
        public string CleaningsPlus { get; set; }
        public string XRaysPlus { get; set; }
        public string BasicPlus { get; set; }
        public string MajorPlus { get; set; }
        public string OrthodonticsPlus { get; set; }
        public string PlanDescription { get; set; }
    }
}
