//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITECORELOCATION
    {
        public int ID { get; set; }
        public string NCID { get; set; }
        public string SITECORE_GUID { get; set; }
        public string WEBSITE { get; set; }
    }
}
