//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEPEXPRESSREGISTRATION
    {
        public string SCHOOL_NAME { get; set; }
        public string DISTRICT { get; set; }
        public string SCHOOL_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string SCHOOL_PHONE_NUMBER { get; set; }
        public Nullable<bool> PRIVATE_SCHOOL { get; set; }
        public Nullable<bool> PREVIOUSLY_PARTICIPATED { get; set; }
        public string PRINCIPALS_NAME { get; set; }
        public string SCHOOL_EMAIL { get; set; }
        public Nullable<long> NUMBER_OF_LESSON_PLAN_BINDERS_REQUIRED { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_1 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_1 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_1 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_1 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_2 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_2 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_2 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_2 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_3 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_3 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_3 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_3 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_4 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_4 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_4 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_4 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_5 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_5 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_5 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_5 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_6 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_6 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_6 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_6 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHERNAME_7 { get; set; }
        public string FOURTH_GRADE_CLASS_INFORMATION_CLASSTEACHEREMAIL_7 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_ENGLISH_PARTICIPANTS_7 { get; set; }
        public Nullable<int> FOURTH_GRADE_CLASS_INFORMATION_SPANISH_PARTICIPANTS_7 { get; set; }
        public string PE_SPECIALIST_NAME { get; set; }
        public string PE_SPECIALIST_EMAIL { get; set; }
        public string PERSON_SUBMITTING_REGISTRATION { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> REMAINDER_SOURCE_OTHER_PAST_PARTICIPANT { get; set; }
        public Nullable<bool> REMAINDER_SOURCE_MAILING { get; set; }
        public Nullable<bool> REMAINDER_SOURCE_EMAIL { get; set; }
        public Nullable<bool> REMAINDER_SOURCE_BILLBOARD { get; set; }
        public string REMAINDER_SOURCE_OTHER { get; set; }
        public string ADDITIONAL_COMMENTS_NEEDS { get; set; }
        public System.DateTime REGISTRATION_DATETIME { get; set; }
    }
}
