//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVL9.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBRESOURCE
    {
        public int WEBRESOURCE_ID { get; set; }
        public Nullable<int> PRVDR_ID { get; set; }
        public string URL { get; set; }
        public string TITLE { get; set; }
        public string RESOURCE_DSC { get; set; }
    
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
